##                              Lec 01 - Introduction to Numpy
##                              Lec 02 - Installation & Usage

In [8]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


##                              Lec 03 - Python list VS Numpy array

In [2]:
import numpy as np
import time

In [3]:
# see the difference between the python list and numpy array executation time. 

size = 100_00_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()

print(f"Total executation time for Python List = {end-start}")

# Numpy array
np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"Total executation time for Numpy Array = {end-start}")

Total executation time for Python List = 1.4660134315490723
Total executation time for Numpy Array = 0.030749797821044922


In [10]:
# observer how much memoery occupied by the python list and numpy array

import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"python list size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
python list size = 80000000 bytes


## Lec 04 - Creating Numpy array from List

In [21]:
# create numpy array from list 

arr = np.array([1,2,3,4,5])
print(arr, arr.dtype, arr.shape)

arr = np.array([1,2,3,4,5,"prime"])
print(arr, arr.dtype, arr.shape)

# 2D array - 2 dimensional 

arr2D = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
print(arr2D, arr2D.dtype, arr2D.shape)

[1 2 3 4 5] int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 (3, 3)


## Lec 05 - Creating Array (Using built-in methods)

In [37]:
arr1 = np.zeros((2,3)) # prefill zeros on all index
print(f"zero method - {arr1}")

arr2 = np.zeros((2,3), dtype = "int64") # set data type to "int"
print(f"zeros with integer format \n {arr2}")

arr3 = np.ones( (5,), dtype = "int64") # prefill with 1 * value times)
print(f"one method \n {arr3, type(arr3)}")  # this properties set value in float type. set data type to "int64"

arr4 = np.full((3,4), 100) #prefill with val ( e.g. 100)
print(arr4, arr4.shape)

arr5 = np.eye(3) # identity matrix
print(arr5, arr5.shape) #Diginoally set value 1.

arr6 = np.arange(1,11,2) # range elements
print(arr6)

arr7 = np.linspace(1,100,4) # evenly spaced array
print(arr7)

arr8 = np.linspace(2,100,3) # evenly spaced array
print(arr8)


zero method - [[0. 0. 0.]
 [0. 0. 0.]]
zeros with integer format 
 [[0 0 0]
 [0 0 0]]
one method 
 (array([1, 1, 1, 1, 1]), <class 'numpy.ndarray'>)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9]
[  1.  34.  67. 100.]
[  2.  51. 100.]


## Lec 06 - Array properties

In [41]:
arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(arr)

print(arr.shape) # dimensions = m x n
print(arr.size) # tot element 
print(arr.dtype) # data type of array
print(arr.ndim) # total number of dimension

float_arr = arr.astype(np.float64) # type casting - int64 => float64
print(float_arr, float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


## Lec 07 - Reshaping Array

In [44]:
arr = np.array([ [1,2,3], [4,5,6], ])
print(arr, arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped, reshaped.shape)

flatten_arr = arr.flatten() # convert 2D => 1D array
print(flatten_arr, flatten_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


## Lec 08 - Indexing on Array

In [48]:
arr = np.array([1,2,3,4,5]) # 1D array
print(arr[0])

arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])  # 2D array
print(arr[0][1])
print(arr[1][2])

# fancy Indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,4]
print(arr[idx])

# Boolean indexing

print(arr[arr >2]) # 


1
2
6
[1 2 5]
