##                              Lec 01 - Introduction to Numpy
##                              Lec 02 - Installation & Usage

In [2]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


##                              Lec 03 - Python list VS Numpy array

In [2]:
import numpy as np
import time

In [3]:
# see the difference between the python list and numpy array executation time. 

size = 100_00_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()

print(f"Total executation time for Python List = {end-start}")

# Numpy array
np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"Total executation time for Numpy Array = {end-start}")

Total executation time for Python List = 1.4660134315490723
Total executation time for Numpy Array = 0.030749797821044922


In [10]:
# observer how much memoery occupied by the python list and numpy array

import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"python list size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
python list size = 80000000 bytes


## Lec 04 - Creating Numpy array from List

In [21]:
# create numpy array from list 

arr = np.array([1,2,3,4,5])
print(arr, arr.dtype, arr.shape)

arr = np.array([1,2,3,4,5,"prime"])
print(arr, arr.dtype, arr.shape)

# 2D array - 2 dimensional 

arr2D = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
print(arr2D, arr2D.dtype, arr2D.shape)

[1 2 3 4 5] int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 (3, 3)


## Lec 05 - Creating Array (Using built-in methods)

In [37]:
arr1 = np.zeros((2,3)) # prefill zeros on all index
print(f"zero method - {arr1}")

arr2 = np.zeros((2,3), dtype = "int64") # set data type to "int"
print(f"zeros with integer format \n {arr2}")

arr3 = np.ones( (5,), dtype = "int64") # prefill with 1 * value times)
print(f"one method \n {arr3, type(arr3)}")  # this properties set value in float type. set data type to "int64"

arr4 = np.full((3,4), 100) #prefill with val ( e.g. 100)
print(arr4, arr4.shape)

arr5 = np.eye(3) # identity matrix
print(arr5, arr5.shape) #Diginoally set value 1.

arr6 = np.arange(1,11,2) # range elements
print(arr6)

arr7 = np.linspace(1,100,4) # evenly spaced array
print(arr7)

arr8 = np.linspace(2,100,3) # evenly spaced array
print(arr8)


zero method - [[0. 0. 0.]
 [0. 0. 0.]]
zeros with integer format 
 [[0 0 0]
 [0 0 0]]
one method 
 (array([1, 1, 1, 1, 1]), <class 'numpy.ndarray'>)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9]
[  1.  34.  67. 100.]
[  2.  51. 100.]


## Lec 06 - Array properties

In [41]:
arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(arr)

print(arr.shape) # dimensions = m x n
print(arr.size) # tot element 
print(arr.dtype) # data type of array
print(arr.ndim) # total number of dimension

float_arr = arr.astype(np.float64) # type casting - int64 => float64
print(float_arr, float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


## Lec 07 - Reshaping Array

In [44]:
arr = np.array([ [1,2,3], [4,5,6], ])
print(arr, arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped, reshaped.shape)

flatten_arr = arr.flatten() # convert 2D => 1D array
print(flatten_arr, flatten_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


## Lec 08 - Indexing on Array

In [48]:
arr = np.array([1,2,3,4,5]) # 1D array
print(arr[0])

arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])  # 2D array
print(arr[0][1])
print(arr[1][2])

# fancy Indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,4]
print(arr[idx])

# Boolean indexing

print(arr[arr >2]) # 


1
2
6
[1 2 5]


## Lec 09 - Slicing Array

In [3]:
# slicing 
arr = np.array([1,2,3,4,5])
# slicing => [start, end, step] like python list. 

print(arr[1:4])
print(arr[:4])
print(arr[:])
print(arr[::])
print(arr[::2])


[2 3 4]
[1 2 3 4]
[1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]


### Copy v/s View

In [17]:
# Copy vs View slincing

# sliced list is a copy

py_list = [1,2,3,4,5]
copy_list = py_list[1:4] # [2,3,4]
copy_list[1]=32

print(copy_list)
print(py_list)
# when on list - applying slicing method on list it will give us a copy of the index. 
#if we change the value of elements it will never be reflected / affected original array


# Sliced array is a view

# But in Numpy array apply slicing method and it will create a view not a copy. view means it's give us original address of element. 
# if change in view index it will 100% affect original array. 

np_arr = np.array([1,2,3,4,5])
view_arr = np_arr[1:4] #[2,3,4]
view_arr[1] = 98

print(view_arr)
print(np_arr)

# If we want to create a view of Numpy array without affecting original array + or we want to create a copy of numpy aray and we want to change the value of 
# view element that time used " .copy() ". It is create a copy of the slicing view. not a create a copy of Numpy array. 

# Creating a copy
copy_arr = np_arr[1:4].copy() # [2,3,4]
copy_arr[2] = 100
print(copy_arr)
print(np_arr)


[2, 32, 4]
[1, 2, 3, 4, 5]
[ 2 98  4]
[ 1  2 98  4  5]
[  2  98 100]
[ 1  2 98  4  5]


## Lec 11 - Common Numpy Data Types

In [18]:
# These Data is commonly used data. 
# Using these data type we can chage the type of data type into int 64 to int 32 bit. 
# usecase - Suppose we want to store value of age and age is maximim is 150 - 200.those data convert it into 64 bit to 32 bit. (reduce memory uses)

arr = np.array([1,2,3,4,5])
arr2 = np.array([1.0, 2.0, 3.0, 4.0])
arr3 = np.array(["hello", "world", "prime", "AI/ML"])

# print Data type of the array
print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes) # 5 elements * 8 bytes each => 40

# change data type using " array_name.astype("float64) "
new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1,2,3,4,5], dtype="float64")
print(new_arr)

# complex Number
arr1 = np.array([2+3j])
arr2 = np.array([5+8j])

print(arr1, arr1.dtype)

# addtion and substraction of complex number

print(arr1 + arr2)
print(arr2 - arr1)



int64
float64
<U5
40
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.]
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]


## Lec 12 - Multi Dimensional Arrays & Axes

### Multi-dimensional arrays in NumPy are the foundation of most scientific and
### machine-learning work.
### A NumPy array can have any number of dimensions (1D, 2D, 3D & so on). Each
### dimension is called an axis.
### • 1D array has 1 axis (axis0).
### • 2D array has 2 axes (axis0 = rows, axis1 = columns)
### • 3D array has 3 axes (axis0 = depth/layer, axis1 = rows in each layer, axis2 =
### columns in each layer)